# Custom Language File for Launcher Customizer

[ejs.app]
title = "OmegaMC Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A SU OMEGAMC LAUNHCHER"
welcomeDescription = "Sei a pochi passi da OmegaMC Launcher"
welcomeDescCTA = "Copyright © 2025 OmegaMC Launcher"
